### ISSUE TITLE
webrick is no longer bundled with Ruby

### ISSUE THREAD

**Issue by lorenzoantei** [zerostaticthemes/jekyll-atlantic-theme#2]
[As of Ruby 3.0, WEBrick is no longer bundled with Ruby, so it needs to be listed as a dependency of Jekyll.](https://github.com/jekyll/jekyll/pull/8524#issue-774749064)

Fix it:
> npm install
> bundle add webrick
> bundle install

After that, you can serve:

> bundle exec jekyll serve

**Comment by JugglerX** [comment]
@lorenzoantei if we add webrick will it still work with Ruby 2? I'm not sure how many people use Ruby 3.
